controllers:
    resource: ../src/Controller/
    type: attribute

company:
  path: /company
  controller: App\Controller\CompanyController::loadTemplate


company_add:
    path: /company/add
    controller: App\Controller\CompanyController::add
    methods: POST

company_list:
  path: /company/list
  controller: App\Controller\CompanyController::list
  methods: GET

company_update:
  path: /company/update/{id}
  controller: App\Controller\CompanyController::update
  methods: PUT

company_delete:
  path: /company/delete/{id}
  controller: App\Controller\CompanyController::delete
  methods: DELETE

company_get_by_id:
  path: /company/id/{id}
  controller: App\Controller\CompanyController::getCompanyById
  methods: GET

company_get_by_name:
  path: /company/name/{name}
  controller: App\Controller\CompanyController::getCompanyByName
  methods: GET

company_get_by_like_name:
  path: /company/like/{name}
  controller: App\Controller\CompanyController::getCompanyByLikeName
  methods: GET

jobs:
  path: /jobs
  controller: App\Controller\JobController::loadTemplate

jobs_add:
  path: /jobs/add
  controller: App\Controller\JobController::add
  methods: POST

jobs_list:
  path: /jobs/list
  controller: App\Controller\JobController::list
  methods: GET

jobs_update:
  path: /jobs/update/{id}
  controller: App\Controller\JobController::update
  methods: PUT

jobs_delete:
  path: /jobs/delete/{id}
  controller: App\Controller\JobController::delete
  methods: DELETE

jobs_get_by_id:
  path: /jobs/id/{id}
  controller: App\Controller\JobController::getJobById
  methods: GET

jobs_get_by_name:
  path: /jobs/name/{name}
  controller: App\Controller\JobController::getJobByName
  methods: GET

jobs_get_by_like_name:
  path: /jobs/like/{name}
  controller: App\Controller\JobController::getJobByLikeName
  methods: GET

contact:
    path: /contact
    controller: App\Controller\ContactController::loadTemplate

contact_add:
    path: /contact/add
    controller: App\Controller\ContactController::add
    methods: POST

home:
    path: /home
    controller: App\Controller\HomeController::loadTemplate

jobs_test:
    path: /jobs/bulk
    controller: App\Controller\JobController::bulk
    methods: POST
