controllers:
    resource: ../src/Controller/
    type: attribute

company:
  path: /company
  controller: App\Controller\CompanyController::loadTemplate


company_add:
    path: /company/add
    controller: App\Controller\CompanyController::add

contact:
    path: /contact
    controller: App\Controller\ContactController::loadTemplate

contact_add:
    path: /contact/add
    controller: App\Controller\ContactController::add

home:
    path: /home
    controller: App\Controller\HomeController::loadTemplate
