controllers:
    resource: ../src/Controller/
    type: attribute

company:
  path: /company
  controller: App\Controller\CompanyController::loadTemplate


company_add:
    path: /company/add
    controller: App\Controller\CompanyController::add

contact_show:
    path: /contact/show
    controller: App\Controller\ContactController::show

home_show:
    path: /home/show
    controller: App\Controller\HomeController::show
